CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(30),
    AUTHOR VARCHAR(20),
    PRICE DOUBLE,
    PUBLICATION_YEAR INT,
    STOCK_AMOUNT INT
);

CREATE TABLE IF NOT EXISTS BILLING_BOOKS (
    BILLING_BOOK_ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(30),
    AUTHOR VARCHAR(20),
    PUBLICATION_YEAR INT,
    ORDER_AMOUNT INT,
    DISCOUNT DOUBLE,
    PRICE DOUBLE,
    TOTAL_AMOUNT DOUBLE,
    BILL_ID BIGINT,
    FOREIGN KEY (BILL_ID) REFERENCES BILLS
);

CREATE TABLE IF NOT EXISTS BILLS (
    BILL_ID BIGINT PRIMARY KEY,
    DATE DATE,
    TOTAL_PRICE DOUBLE
);
